### PR TITLE
simplify test

### PR DESCRIPTION
**Pull request by Kibbey**
-Removed old solution.
-Updated Readme

### CODE REVIEW

**Comment by Jonahss** [comment]
The team is in favor of this. @Techwraith what do you think?

The idea here is make the aims of the .Net homework more clearly defined, but remove our pre-written solution since it may have just confused people, and starting from a clean slate may show us more about them.

**Comment by Techwraith** [comment]
I'm not sure I like starting without a base - part of what I like with a starting solution is that it will show us how they'll interact with a pre-existing system. That said, the instructions are much clearer, so I'm happy about that.

If the team wants to do it, I'll happily disagree and commit.

**Comment by Jonahss** [comment]
It's a fair point about seeing how someone uses an existing system, but really, I think the majority of dotnet developers spend most their career working on pre-existing projects, and devs who have experience starting a new project tend to be the ones who have a deeper knowledge of the system.

@rbenoit any comments?

**Comment by rbenoit** [comment]
So I've been thinking about this - I definitely see @Jonahss  point about working with an existing system. However, I don't think we provide enough existing implementation to get an idea about how the candidate works with legacy code base, so it feels still to me like it adds more confusion than clarity.

**Comment by Jonahss** [comment]
let's give it a trial run.

**Pull request merged**
